/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiceAgreementRouteImport } from './routes/service-agreement'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as InsuranceClaimRejectedRouteImport } from './routes/insurance-claim-rejected'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ClaimHelpRouteImport } from './routes/claim-help'
import { Route as AppreciationRouteImport } from './routes/appreciation'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AuthVerifiedRouteImport } from './routes/auth.verified'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AdminRewardsRouteImport } from './routes/admin.rewards'
import { Route as AdminPromocodesRouteImport } from './routes/admin.promocodes'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminNoticesRouteImport } from './routes/admin.notices'
import { Route as AdminMailTestRouteImport } from './routes/admin.mail-test'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardRewardsRouteImport } from './routes/_authenticated/dashboard.rewards'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardInvoicesRouteImport } from './routes/_authenticated/dashboard.invoices'
import { Route as AuthenticatedDashboardClaimsIndexRouteImport } from './routes/_authenticated/dashboard.claims.index'
import { Route as AuthenticatedDashboardPayClaimIdRouteImport } from './routes/_authenticated/dashboard.pay.$claimId'
import { Route as AuthenticatedDashboardDeclareClaimIdRouteImport } from './routes/_authenticated/dashboard.declare.$claimId'
import { Route as AuthenticatedDashboardClaimsNewRouteImport } from './routes/_authenticated/dashboard.claims.new'
import { Route as AuthenticatedDashboardClaimsIdRouteImport } from './routes/_authenticated/dashboard.claims.$id'
import { Route as AuthenticatedDashboardAgreementClaimIdRouteImport } from './routes/_authenticated/dashboard.agreement.$claimId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAgreementRoute = ServiceAgreementRouteImport.update({
  id: '/service-agreement',
  path: '/service-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceClaimRejectedRoute = InsuranceClaimRejectedRouteImport.update({
  id: '/insurance-claim-rejected',
  path: '/insurance-claim-rejected',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimHelpRoute = ClaimHelpRouteImport.update({
  id: '/claim-help',
  path: '/claim-help',
  getParentRoute: () => rootRouteImport,
} as any)
const AppreciationRoute = AppreciationRouteImport.update({
  id: '/appreciation',
  path: '/appreciation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifiedRoute = AuthVerifiedRouteImport.update({
  id: '/auth/verified',
  path: '/auth/verified',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRewardsRoute = AdminRewardsRouteImport.update({
  id: '/admin/rewards',
  path: '/admin/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromocodesRoute = AdminPromocodesRouteImport.update({
  id: '/admin/promocodes',
  path: '/admin/promocodes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/admin/payouts',
  path: '/admin/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/admin/notices',
  path: '/admin/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMailTestRoute = AdminMailTestRouteImport.update({
  id: '/admin/mail-test',
  path: '/admin/mail-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/admin/invoices',
  path: '/admin/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRewardsRoute =
  AuthenticatedDashboardRewardsRouteImport.update({
    id: '/dashboard/rewards',
    path: '/dashboard/rewards',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/dashboard/profile',
    path: '/dashboard/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardInvoicesRoute =
  AuthenticatedDashboardInvoicesRouteImport.update({
    id: '/dashboard/invoices',
    path: '/dashboard/invoices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardClaimsIndexRoute =
  AuthenticatedDashboardClaimsIndexRouteImport.update({
    id: '/dashboard/claims/',
    path: '/dashboard/claims/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardPayClaimIdRoute =
  AuthenticatedDashboardPayClaimIdRouteImport.update({
    id: '/dashboard/pay/$claimId',
    path: '/dashboard/pay/$claimId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardDeclareClaimIdRoute =
  AuthenticatedDashboardDeclareClaimIdRouteImport.update({
    id: '/dashboard/declare/$claimId',
    path: '/dashboard/declare/$claimId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardClaimsNewRoute =
  AuthenticatedDashboardClaimsNewRouteImport.update({
    id: '/dashboard/claims/new',
    path: '/dashboard/claims/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardClaimsIdRoute =
  AuthenticatedDashboardClaimsIdRouteImport.update({
    id: '/dashboard/claims/$id',
    path: '/dashboard/claims/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAgreementClaimIdRoute =
  AuthenticatedDashboardAgreementClaimIdRouteImport.update({
    id: '/dashboard/agreement/$claimId',
    path: '/dashboard/agreement/$claimId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/appreciation': typeof AppreciationRoute
  '/claim-help': typeof ClaimHelpRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/insurance-claim-rejected': typeof InsuranceClaimRejectedRoute
  '/policies': typeof PoliciesRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service-agreement': typeof ServiceAgreementRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mail-test': typeof AdminMailTestRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/promocodes': typeof AdminPromocodesRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/invoices': typeof AuthenticatedDashboardInvoicesRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/rewards': typeof AuthenticatedDashboardRewardsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/agreement/$claimId': typeof AuthenticatedDashboardAgreementClaimIdRoute
  '/dashboard/claims/$id': typeof AuthenticatedDashboardClaimsIdRoute
  '/dashboard/claims/new': typeof AuthenticatedDashboardClaimsNewRoute
  '/dashboard/declare/$claimId': typeof AuthenticatedDashboardDeclareClaimIdRoute
  '/dashboard/pay/$claimId': typeof AuthenticatedDashboardPayClaimIdRoute
  '/dashboard/claims/': typeof AuthenticatedDashboardClaimsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/appreciation': typeof AppreciationRoute
  '/claim-help': typeof ClaimHelpRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/insurance-claim-rejected': typeof InsuranceClaimRejectedRoute
  '/policies': typeof PoliciesRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service-agreement': typeof ServiceAgreementRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mail-test': typeof AdminMailTestRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/promocodes': typeof AdminPromocodesRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard/invoices': typeof AuthenticatedDashboardInvoicesRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/rewards': typeof AuthenticatedDashboardRewardsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/agreement/$claimId': typeof AuthenticatedDashboardAgreementClaimIdRoute
  '/dashboard/claims/$id': typeof AuthenticatedDashboardClaimsIdRoute
  '/dashboard/claims/new': typeof AuthenticatedDashboardClaimsNewRoute
  '/dashboard/declare/$claimId': typeof AuthenticatedDashboardDeclareClaimIdRoute
  '/dashboard/pay/$claimId': typeof AuthenticatedDashboardPayClaimIdRoute
  '/dashboard/claims': typeof AuthenticatedDashboardClaimsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/appreciation': typeof AppreciationRoute
  '/claim-help': typeof ClaimHelpRoute
  '/disclaimer': typeof DisclaimerRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/insurance-claim-rejected': typeof InsuranceClaimRejectedRoute
  '/policies': typeof PoliciesRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service-agreement': typeof ServiceAgreementRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mail-test': typeof AdminMailTestRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/promocodes': typeof AdminPromocodesRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/dashboard/invoices': typeof AuthenticatedDashboardInvoicesRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/rewards': typeof AuthenticatedDashboardRewardsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/agreement/$claimId': typeof AuthenticatedDashboardAgreementClaimIdRoute
  '/_authenticated/dashboard/claims/$id': typeof AuthenticatedDashboardClaimsIdRoute
  '/_authenticated/dashboard/claims/new': typeof AuthenticatedDashboardClaimsNewRoute
  '/_authenticated/dashboard/declare/$claimId': typeof AuthenticatedDashboardDeclareClaimIdRoute
  '/_authenticated/dashboard/pay/$claimId': typeof AuthenticatedDashboardPayClaimIdRoute
  '/_authenticated/dashboard/claims/': typeof AuthenticatedDashboardClaimsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/appreciation'
    | '/claim-help'
    | '/disclaimer'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/insurance-claim-rejected'
    | '/policies'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/service-agreement'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/invoices'
    | '/admin/login'
    | '/admin/mail-test'
    | '/admin/notices'
    | '/admin/payouts'
    | '/admin/promocodes'
    | '/admin/rewards'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset'
    | '/auth/signup'
    | '/auth/verified'
    | '/auth/verify'
    | '/admin/'
    | '/dashboard/invoices'
    | '/dashboard/profile'
    | '/dashboard/rewards'
    | '/dashboard/'
    | '/dashboard/agreement/$claimId'
    | '/dashboard/claims/$id'
    | '/dashboard/claims/new'
    | '/dashboard/declare/$claimId'
    | '/dashboard/pay/$claimId'
    | '/dashboard/claims/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/appreciation'
    | '/claim-help'
    | '/disclaimer'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/insurance-claim-rejected'
    | '/policies'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/service-agreement'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/invoices'
    | '/admin/login'
    | '/admin/mail-test'
    | '/admin/notices'
    | '/admin/payouts'
    | '/admin/promocodes'
    | '/admin/rewards'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset'
    | '/auth/signup'
    | '/auth/verified'
    | '/auth/verify'
    | '/admin'
    | '/dashboard/invoices'
    | '/dashboard/profile'
    | '/dashboard/rewards'
    | '/dashboard'
    | '/dashboard/agreement/$claimId'
    | '/dashboard/claims/$id'
    | '/dashboard/claims/new'
    | '/dashboard/declare/$claimId'
    | '/dashboard/pay/$claimId'
    | '/dashboard/claims'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$'
    | '/about'
    | '/appreciation'
    | '/claim-help'
    | '/disclaimer'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/insurance-claim-rejected'
    | '/policies'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/service-agreement'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/invoices'
    | '/admin/login'
    | '/admin/mail-test'
    | '/admin/notices'
    | '/admin/payouts'
    | '/admin/promocodes'
    | '/admin/rewards'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset'
    | '/auth/signup'
    | '/auth/verified'
    | '/auth/verify'
    | '/admin/'
    | '/_authenticated/dashboard/invoices'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/rewards'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/agreement/$claimId'
    | '/_authenticated/dashboard/claims/$id'
    | '/_authenticated/dashboard/claims/new'
    | '/_authenticated/dashboard/declare/$claimId'
    | '/_authenticated/dashboard/pay/$claimId'
    | '/_authenticated/dashboard/claims/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AppreciationRoute: typeof AppreciationRoute
  ClaimHelpRoute: typeof ClaimHelpRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  InsuranceClaimRejectedRoute: typeof InsuranceClaimRejectedRoute
  PoliciesRoute: typeof PoliciesRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServiceAgreementRoute: typeof ServiceAgreementRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMailTestRoute: typeof AdminMailTestRoute
  AdminNoticesRoute: typeof AdminNoticesRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminPromocodesRoute: typeof AdminPromocodesRoute
  AdminRewardsRoute: typeof AdminRewardsRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifiedRoute: typeof AuthVerifiedRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-agreement': {
      id: '/service-agreement'
      path: '/service-agreement'
      fullPath: '/service-agreement'
      preLoaderRoute: typeof ServiceAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance-claim-rejected': {
      id: '/insurance-claim-rejected'
      path: '/insurance-claim-rejected'
      fullPath: '/insurance-claim-rejected'
      preLoaderRoute: typeof InsuranceClaimRejectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim-help': {
      id: '/claim-help'
      path: '/claim-help'
      fullPath: '/claim-help'
      preLoaderRoute: typeof ClaimHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appreciation': {
      id: '/appreciation'
      path: '/appreciation'
      fullPath: '/appreciation'
      preLoaderRoute: typeof AppreciationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verified': {
      id: '/auth/verified'
      path: '/auth/verified'
      fullPath: '/auth/verified'
      preLoaderRoute: typeof AuthVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rewards': {
      id: '/admin/rewards'
      path: '/admin/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AdminRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promocodes': {
      id: '/admin/promocodes'
      path: '/admin/promocodes'
      fullPath: '/admin/promocodes'
      preLoaderRoute: typeof AdminPromocodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/admin/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/admin/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mail-test': {
      id: '/admin/mail-test'
      path: '/admin/mail-test'
      fullPath: '/admin/mail-test'
      preLoaderRoute: typeof AdminMailTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/admin/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/rewards': {
      id: '/_authenticated/dashboard/rewards'
      path: '/dashboard/rewards'
      fullPath: '/dashboard/rewards'
      preLoaderRoute: typeof AuthenticatedDashboardRewardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/invoices': {
      id: '/_authenticated/dashboard/invoices'
      path: '/dashboard/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof AuthenticatedDashboardInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/claims/': {
      id: '/_authenticated/dashboard/claims/'
      path: '/dashboard/claims'
      fullPath: '/dashboard/claims/'
      preLoaderRoute: typeof AuthenticatedDashboardClaimsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/pay/$claimId': {
      id: '/_authenticated/dashboard/pay/$claimId'
      path: '/dashboard/pay/$claimId'
      fullPath: '/dashboard/pay/$claimId'
      preLoaderRoute: typeof AuthenticatedDashboardPayClaimIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/declare/$claimId': {
      id: '/_authenticated/dashboard/declare/$claimId'
      path: '/dashboard/declare/$claimId'
      fullPath: '/dashboard/declare/$claimId'
      preLoaderRoute: typeof AuthenticatedDashboardDeclareClaimIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/claims/new': {
      id: '/_authenticated/dashboard/claims/new'
      path: '/dashboard/claims/new'
      fullPath: '/dashboard/claims/new'
      preLoaderRoute: typeof AuthenticatedDashboardClaimsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/claims/$id': {
      id: '/_authenticated/dashboard/claims/$id'
      path: '/dashboard/claims/$id'
      fullPath: '/dashboard/claims/$id'
      preLoaderRoute: typeof AuthenticatedDashboardClaimsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/agreement/$claimId': {
      id: '/_authenticated/dashboard/agreement/$claimId'
      path: '/dashboard/agreement/$claimId'
      fullPath: '/dashboard/agreement/$claimId'
      preLoaderRoute: typeof AuthenticatedDashboardAgreementClaimIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardInvoicesRoute: typeof AuthenticatedDashboardInvoicesRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardRewardsRoute: typeof AuthenticatedDashboardRewardsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardAgreementClaimIdRoute: typeof AuthenticatedDashboardAgreementClaimIdRoute
  AuthenticatedDashboardClaimsIdRoute: typeof AuthenticatedDashboardClaimsIdRoute
  AuthenticatedDashboardClaimsNewRoute: typeof AuthenticatedDashboardClaimsNewRoute
  AuthenticatedDashboardDeclareClaimIdRoute: typeof AuthenticatedDashboardDeclareClaimIdRoute
  AuthenticatedDashboardPayClaimIdRoute: typeof AuthenticatedDashboardPayClaimIdRoute
  AuthenticatedDashboardClaimsIndexRoute: typeof AuthenticatedDashboardClaimsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardInvoicesRoute: AuthenticatedDashboardInvoicesRoute,
  AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
  AuthenticatedDashboardRewardsRoute: AuthenticatedDashboardRewardsRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDashboardAgreementClaimIdRoute:
    AuthenticatedDashboardAgreementClaimIdRoute,
  AuthenticatedDashboardClaimsIdRoute: AuthenticatedDashboardClaimsIdRoute,
  AuthenticatedDashboardClaimsNewRoute: AuthenticatedDashboardClaimsNewRoute,
  AuthenticatedDashboardDeclareClaimIdRoute:
    AuthenticatedDashboardDeclareClaimIdRoute,
  AuthenticatedDashboardPayClaimIdRoute: AuthenticatedDashboardPayClaimIdRoute,
  AuthenticatedDashboardClaimsIndexRoute:
    AuthenticatedDashboardClaimsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AppreciationRoute: AppreciationRoute,
  ClaimHelpRoute: ClaimHelpRoute,
  DisclaimerRoute: DisclaimerRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  InsuranceClaimRejectedRoute: InsuranceClaimRejectedRoute,
  PoliciesRoute: PoliciesRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServiceAgreementRoute: ServiceAgreementRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMailTestRoute: AdminMailTestRoute,
  AdminNoticesRoute: AdminNoticesRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminPromocodesRoute: AdminPromocodesRoute,
  AdminRewardsRoute: AdminRewardsRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetRoute: AuthResetRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifiedRoute: AuthVerifiedRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
